name: HelloWorld
description: ''
version: 0.0.1-SNAPSHOT
author: null
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: helloworld
  parentArtefactID: ''
  buildSystem: wheel
  author: null
  createdAt: '2023-05-30 05:21:56'
  modifiedAt: '2023-05-30 05:21:56'
pipelines:
  pipelines/customers_orders:
    name: customers_orders
    description: Aggregates total spending's for each customer
    author: prakash.choudhary@prutech.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-05-30 05:21:57'
    modifiedAt: '2023-05-30 05:21:57'
    datasets:
      inputs:
      - datasets/orders
      - datasets/customers
      outputs:
      - datasets/customers_orders
    subgraphs: []
    dependencies: {}
  pipelines/report_top_customers:
    name: report_top_customers
    description: Prepare a report based on customers' spending
    author: prakash.choudhary@prutech.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-05-30 05:21:57'
    modifiedAt: '2023-05-30 05:21:57'
    datasets:
      inputs:
      - datasets/customers_orders
      outputs:
      - datasets/report
    subgraphs: []
    dependencies: {}
  pipelines/join_agg_sort:
    name: join_agg_sort
    description: Show an example of joining two datasets (customers and orders), aggregating
      (sales by customer), sorting (by totals)
    author: prakash.choudhary@prutech.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-05-30 05:21:57'
    modifiedAt: '2023-05-30 05:21:57'
    datasets:
      inputs:
      - datasets/orders
      - datasets/customers
      outputs:
      - datasets/customer_totals
    subgraphs: []
    dependencies: {}
  pipelines/farmers-markets-irs:
    name: farmers-markets-irs
    description: Exploration of Farmer's Market Locations By US Zip Code
    author: prakash.choudhary@prutech.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-05-30 05:21:57'
    modifiedAt: '2023-05-30 05:21:58'
    datasets:
      inputs:
      - datasets/irs-zipcode-data
      - datasets/farmers-markets
      outputs:
      - datasets/farmers_market_tax_report
    subgraphs: []
    dependencies: {}
datasets:
  datasets/report:
    name: report
    description: Final report for the bank
    author: prakash.choudhary@prutech.com
    createdAt: '2023-05-30 05:21:56'
    modifiedAt: '2023-05-30 05:21:56'
    mode: batch
    physicalDatasets:
      Trial:
        fabricId: 1935
        datasetType: File
        description: ''
        author: prakash.choudhary@prutech.com
        createdAt: '2023-05-30 05:21:56'
        modifiedAt: '2023-05-30 05:21:56'
  datasets/customer_totals:
    name: customer_totals
    description: Customers by total of their purchases
    author: prakash.choudhary@prutech.com
    createdAt: '2023-05-30 05:21:56'
    modifiedAt: '2023-05-30 05:21:57'
    mode: batch
    physicalDatasets:
      Trial:
        fabricId: 1935
        datasetType: File
        description: ''
        author: prakash.choudhary@prutech.com
        createdAt: '2023-05-30 05:21:56'
        modifiedAt: '2023-05-30 05:21:56'
  datasets/orders:
    name: orders
    description: All the orders placed by the customers
    author: prakash.choudhary@prutech.com
    createdAt: '2023-05-30 05:21:57'
    modifiedAt: '2023-05-30 05:21:57'
    mode: batch
    physicalDatasets:
      Trial:
        fabricId: 1935
        datasetType: File
        description: ''
        author: prakash.choudhary@prutech.com
        createdAt: '2023-05-30 05:21:57'
        modifiedAt: '2023-05-30 05:21:57'
  datasets/customers:
    name: customers
    description: All the customers
    author: prakash.choudhary@prutech.com
    createdAt: '2023-05-30 05:21:57'
    modifiedAt: '2023-05-30 05:21:57'
    mode: batch
    physicalDatasets:
      Trial:
        fabricId: 1935
        datasetType: File
        description: ''
        author: prakash.choudhary@prutech.com
        createdAt: '2023-05-30 05:21:57'
        modifiedAt: '2023-05-30 05:21:57'
  datasets/customers_orders:
    name: customers_orders
    description: Customers by total of their purchases
    author: prakash.choudhary@prutech.com
    createdAt: '2023-05-30 05:21:57'
    modifiedAt: '2023-05-30 05:21:57'
    mode: batch
    physicalDatasets:
      Trial:
        fabricId: 1935
        datasetType: File
        description: ''
        author: prakash.choudhary@prutech.com
        createdAt: '2023-05-30 05:21:57'
        modifiedAt: '2023-05-30 05:21:57'
  datasets/old_events:
    name: old_events
    description: Old events data
    author: prakash.choudhary@prutech.com
    createdAt: '2023-05-30 05:21:57'
    modifiedAt: '2023-05-30 05:21:57'
    mode: batch
    physicalDatasets:
      Trial:
        fabricId: 1935
        datasetType: File
        description: ''
        author: prakash.choudhary@prutech.com
        createdAt: '2023-05-30 05:21:57'
        modifiedAt: '2023-05-30 05:21:57'
  datasets/historic_events_flat:
    name: historic_events_flat
    description: Historic events flat
    author: prakash.choudhary@prutech.com
    createdAt: '2023-05-30 05:21:57'
    modifiedAt: '2023-05-30 05:21:57'
    mode: batch
    physicalDatasets:
      Trial:
        fabricId: 1935
        datasetType: File
        description: ''
        author: prakash.choudhary@prutech.com
        createdAt: '2023-05-30 05:21:57'
        modifiedAt: '2023-05-30 05:21:57'
  datasets/farmers-markets:
    name: farmers-markets
    description: Farmer's Market data
    author: prakash.choudhary@prutech.com
    createdAt: '2023-05-30 05:21:57'
    modifiedAt: '2023-05-30 05:21:57'
    mode: batch
    physicalDatasets:
      Trial:
        fabricId: 1935
        datasetType: File
        description: ''
        author: prakash.choudhary@prutech.com
        createdAt: '2023-05-30 05:21:57'
        modifiedAt: '2023-05-30 05:21:57'
  datasets/irs-zipcode-data:
    name: irs-zipcode-data
    description: Irs zipcode data
    author: prakash.choudhary@prutech.com
    createdAt: '2023-05-30 05:21:57'
    modifiedAt: '2023-05-30 05:21:57'
    mode: batch
    physicalDatasets:
      Trial:
        fabricId: 1935
        datasetType: File
        description: ''
        author: prakash.choudhary@prutech.com
        createdAt: '2023-05-30 05:21:57'
        modifiedAt: '2023-05-30 05:21:57'
  datasets/farmers_market_tax_report:
    name: farmers_market_tax_report
    description: Farmer's market tax report
    author: prakash.choudhary@prutech.com
    createdAt: '2023-05-30 05:21:57'
    modifiedAt: '2023-05-30 05:21:57'
    mode: batch
    physicalDatasets:
      Trial:
        fabricId: 1935
        datasetType: File
        description: ''
        author: prakash.choudhary@prutech.com
        createdAt: '2023-05-30 05:21:57'
        modifiedAt: '2023-05-30 05:21:57'
templates: {}
jobs: {}
functions:
  author: null
  createdAt: '2023-05-30 05:21:56'
  modifiedAt: '2023-05-30 05:21:56'
  gems: {}
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
